services:
  interajai-react:
    container_name: interajai-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - web
